version: '3.1'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=algosolve
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    restart: always

