version: '3.1'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=algosolve
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    expose:
      - "5433"
      - "5432"
    restart: always
    networks:
      algosolved_networks:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/algosolve
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      algosolved_networks:

  web:
    build:
      context: src/main/frontend
      dockerfile: Dockerfile
    working_dir: /usr/src/frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    networks:
      algosolved_networks:


networks:
  algosolved_networks:
    driver: bridge